<?xml version="1.0" encoding="utf-8"?>
<!--
This is an autogenerated file...please run:
	change compile-roles
to regenerate this file.
-->
<{php}>
	$pickerLimit = 5;
	$module = $this->get_template_vars('module');
	$roles = $module->getRoles();
	$rolesCount = count($roles);
	$tabCount = (int)ceil($rolesCount/(float)$pickerLimit);
	$this->assign('needsTabs', $tabCount > 1);
	$tabNames = array();
	for ($i = 0; $i < $tabCount ; $i++)
	{
		$tabNames[] = array("permission-panel-" . ($i+1), array_slice($roles, $i*$pickerLimit, $pickerLimit)); ;
	}
	$this->assign('tabNames', $tabNames);
<{/php}>
<layout xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" xmlns:i18n="http://phptal.motion-twin.com/i18n" xmlns:tal="http://phptal.motion-twin.com/tal" xmlns:change="http://www.rbs-change.eu/change-4.2/taglib/phptal">
<{if $needsTabs}>
	<tabbox flex="1">
   		<tabs flex="1">
		<{foreach from=$tabNames item=tab}>
   			<tab i18n:attributes="label &amp;modules.<{$module->name}>.document.permission.<{$tab[0]|capitalize}>;" change:icon="shield_yellow/small shadow"/>
		<{/foreach}>
   		</tabs>
   		<tabpanels flex="1">
<{/if}>
<{foreach from=$tabNames item=tab}>
	<{if $needsTabs}>
     		<tabpanel id="<{$tab[1]}>" orient="vertical">
	<{/if}>
   			<grid flex="1">
    				<columns>
      					<column />
      					<column flex="1" />
    				</columns>
    				<rows>
	<{foreach from=$tab[1] item=role}>
      					<row>
      						<wlabel i18n:attributes="value &amp;modules.<{$module->name}>.document.permission.<{$role->getName()|capitalize}>;"/>
		<{if $role->isFrontEnd()}>
							<welementpicker  type="droppable" allow="<{$module->classFrontList}>" i18n:attributes="label &amp;modules.<{$module->name}>.document.permission.<{$role->getName()|capitalize}>;"  name = "<{$role->getName()}>">
								<whelp i18n:translate="&amp;modules.<{$module->name}>.document.permission.<{$role->getName()|capitalize}>-help;" />
							</welementpicker>
		<{else}>
							<welementpicker  type="droppable" allow="<{$module->classBackList}>" i18n:attributes="label &amp;modules.<{$module->name}>.document.permission.<{$role->getName()|capitalize}>;"  name = "<{$role->getName()}>">
								<whelp i18n:translate="&amp;modules.<{$module->name}>.document.permission.<{$role->getName()|capitalize}>-help;" />
							</welementpicker>
		<{/if}>
						</row>
	<{/foreach}>
					</rows>
				</grid>
	<{if $needsTabs}>
      	</tabpanel>
    <{/if}>
<{/foreach}>

<{if $needsTabs}>
		</tabpanels>
	</tabbox>
<{/if}>
</layout>